---

- name: Add Elastic APT key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Add Elastic APT repo
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/{{ filebeat_version }}.x/apt stable main"
    filename: "elastic"

- name: Install filebeat
  apt:
    name: filebeat

- name: Copy filebeat configuration
  template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml
  notify: restart filebeat

- name: Enable and start filebeat service
  service:
    name: filebeat
    state: started
    enabled: true
